### ISSUE TITLE
Only 5 max viewers on the scoreboard

### ISSUE THREAD

**Issue by 532637** [2Eggsss/Steam-Viewbot#1]
didnt close the stream/nodejs until competitive end the viewers on scoreboard only showing 5 viewers,
also tried modify the worker value or use the old.js still same issue,
even showing 30k viewers on stream steam overlay but only showing 5 views on scoreboard.
![maxviewer5](https://user-images.githubusercontent.com/65431947/82107916-5ad2cc00-9755-11ea-99ad-7bd2aa6823a7.png)

**Comment by 2Eggsss** [comment]
This is a known issue/glitch which happens due to the way the game relays the information. Those 5 viewers you see are probably the "real" viewers within GOTV. Unfortunately I don't know if there is a real fix for this except to restart the program and/or disconnecting and reconnecting back to the comp game.

**Comment by suicidal** [comment]
Currently I have only seen viewers appear on the GOTV viewer count if they were logged in to a steam account while viewing the stream.  The number will go up and down on the leaderboard after the 5 viewers depending on how many logged in users are on your broadcast

**Comment by suicidal** [comment]
Another way to come to this conclusion is to start up the bot so you get a fair bit of viewers, then close the script running so none of your viewers are bots, which would insinuate you have a legitimate count of 5 viewers in your match

**Comment by 2Eggsss** [comment]
The viewbot seems to be patched now, therefore closing this issue.
